# Generated by Django 4.0.8 on 2023-01-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_district_user_category_user_is_oc_user_is_sp_or_cp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(upload_to='')),
                ('entry_date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name if known')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('missing_or_found', models.CharField(max_length=1, verbose_name='Missing Or Found')),
                ('description', models.CharField(max_length=500)),
                ('height', models.IntegerField()),
                ('face_encoding', models.CharField(blank=True, max_length=2000)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude of Event')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude of Event')),
                ('police_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.policestation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
