# Generated by Django 4.0.8 on 2023-01-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='face_encoding',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
