# Generated by Django 4.0.8 on 2023-01-09 09:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_report_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32643),
        ),
    ]
