# Generated by Django 4.0.8 on 2023-01-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_report_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='year',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
