# Generated by Django 4.0.8 on 2023-01-09 13:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_report_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
