# Generated by Django 4.0.8 on 2023-01-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_report_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSearchResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('context', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='report',
            name='age',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='guardian_name_and_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Name if known'),
        ),
        migrations.AddField(
            model_name='report',
            name='icon',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
