# Generated by Django 4.0.8 on 2023-01-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_reportsearchresults_report_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportSearchResults',
        ),
    ]
