# Generated by Django 4.0.8 on 2023-01-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_delete_reportsearchresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='icon',
            field=models.FileField(blank=True, default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
