# Generated by Django 4.0.8 on 2023-01-15 10:55

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_report_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description_search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reports', models.ManyToManyField(to='backend.report')),
            ],
        ),
    ]
