# Generated by Django 4.0.8 on 2023-01-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_token_reports_report_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tokens',
            field=models.ManyToManyField(related_name='tokens', to='backend.token'),
        ),
    ]
