# Generated by Django 4.0.8 on 2023-01-16 05:51

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_report_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='tokens',
        ),
        migrations.AddIndex(
            model_name='report',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description_search_vector'], name='backend_rep_descrip_8c95c8_gin'),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
