# Generated by Django 4.0.8 on 2023-01-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_report_tokens_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
              CREATE TRIGGER description_search_vector_trigger
              BEFORE INSERT OR UPDATE OF description, description_search_vector
              ON backend_report 
              FOR EACH ROW EXECUTE PROCEDURE
              tsvector_update_trigger(
                description_search_vector, 'pg_catalog.english',description
              );

              UPDATE backend_report  SET description_search_vector = NULL;
            ''',

            reverse_sql = '''
              DROP TRIGGER IF EXISTS description_search_vector_trigger
              ON backend_report ;
            '''
        ),
    ]