# Generated by Django 4.0.8 on 2023-01-16 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_create_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('mail_sent', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='report',
            name='matches',
            field=models.ManyToManyField(related_name='matched_by', through='backend.Match', to='backend.report'),
        ),
        migrations.AddField(
            model_name='report',
            name='reference',
            field=models.IntegerField(default=42, verbose_name='PS Reference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='report_found',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_found', to='backend.report'),
        ),
        migrations.AddField(
            model_name='match',
            name='report_missing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_missing', to='backend.report'),
        ),
    ]
