# Generated by Django 4.0.8 on 2023-01-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_match_report_matches_report_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='face_encoding',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='report',
            name='guardian_name_and_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name if known'),
        ),
        migrations.AlterField(
            model_name='report',
            name='icon',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name if known'),
        ),
    ]
