# Generated by Django 4.0.8 on 2023-01-27 05:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_report_face_encoding_alter_report_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_CODE_DES', models.CharField(max_length=255)),
                ('HYC_DESCRI', models.CharField(max_length=255)),
                ('NAM', models.CharField(max_length=255)),
                ('ISO', models.CharField(max_length=255)),
                ('NAME_0', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
