# Generated by Django 4.0.8 on 2023-01-27 12:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_waterlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterlines',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(geography=True, srid=4326),
        ),
    ]
