# Generated by Django 4.0.8 on 2023-01-27 12:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_waterlines_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FID_rail_d', models.IntegerField()),
                ('F_CODE_DES', models.CharField(max_length=255)),
                ('EXS_DESCRI', models.CharField(max_length=255)),
                ('FCO_DESCRI', models.CharField(max_length=255)),
                ('FID_countr', models.IntegerField()),
                ('ISO', models.CharField(max_length=255)),
                ('ISOCOUNTRY', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(geography=True, srid=4326)),
            ],
        ),
    ]
