# Generated by Django 4.0.8 on 2023-01-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_mitroadlines_mitwaterlines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RailLines',
        ),
        migrations.DeleteModel(
            name='WaterLines',
        ),
    ]
