# Generated by Django 4.0.8 on 2023-02-03 08:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_delete_raillines_delete_waterlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedReportSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('keywords', models.CharField(max_length=100, null=True)),
                ('full_text_search_type', models.IntegerField()),
                ('missing_or_found', models.CharField(max_length=1, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('latitude', models.CharField(max_length=20, null=True)),
                ('longitude', models.CharField(max_length=20, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('distance', models.IntegerField()),
                ('ps_list', models.CharField(max_length=500, null=True)),
                ('districts', models.CharField(max_length=200, null=True)),
                ('min_date', models.DateField()),
                ('max_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
