# Generated by Django 4.0.8 on 2023-02-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_advancedreportsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedreportsearch',
            name='gender',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='advancedreportsearch',
            name='missing_or_found',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
