# Generated by Django 4.0.8 on 2023-02-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_advancedreportsearch_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedreportsearch',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='advancedreportsearch',
            name='full_text_search_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='advancedreportsearch',
            name='max_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='advancedreportsearch',
            name='min_date',
            field=models.DateField(null=True),
        ),
    ]
