# Generated by Django 4.0.8 on 2023-02-04 11:40

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_district_user_category_user_is_oc_user_is_sp_or_cp_and_more'),
        ('backend', '0026_alter_advancedreportsearch_distance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(upload_to='')),
                ('telephone_of_missing', models.CharField(max_length=10)),
                ('telephone_of_reporter', models.CharField(max_length=10)),
                ('icon', models.FileField(null=True, upload_to='')),
                ('entry_date', models.DateField(null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('gender', models.CharField(blank=True, max_length=1, null=True, verbose_name='Gender')),
                ('description', models.CharField(max_length=500)),
                ('description_search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('height', models.IntegerField()),
                ('age', models.IntegerField()),
                ('guardian_name_and_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name if known')),
                ('face_encoding', models.CharField(blank=True, max_length=4000, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('token', models.CharField(max_length=8)),
                ('year', models.CharField(blank=True, max_length=2)),
                ('matches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.report')),
                ('police_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.policestation')),
            ],
        ),
        migrations.AddIndex(
            model_name='publicreport',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description_search_vector'], name='backend_pub_descrip_73db19_gin'),
        ),
    ]
