# Generated by Django 4.0.8 on 2023-02-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_publicreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicreport',
            name='missing_or_found',
            field=models.CharField(default='M', max_length=1, verbose_name='Missing Or Found'),
            preserve_default=False,
        ),
    ]
