# Generated by Django 4.0.8 on 2023-02-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_publicreport_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicreport',
            name='email_of_reporter',
            field=models.EmailField(default='sanjaysingh13@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
