# Generated by Django 4.0.8 on 2023-02-05 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_publicreport_email_of_reporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicreport',
            name='matches',
        ),
        migrations.CreateModel(
            name='PublicReportMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('mail_sent', models.DateField(null=True)),
                ('report_found', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_report_found', to='backend.report')),
                ('report_missing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_report_missing', to='backend.publicreport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
