# Generated by Django 4.0.8 on 2023-02-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_remove_publicreport_matches_publicreportmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='entry_date',
            field=models.DateField(db_index=True),
        ),
    ]
