# Generated by Django 4.0.8 on 2023-02-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_emailrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicreport',
            name='reconciled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='reconciled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('police_station', 'reference', 'entry_date'), name='unique_report'),
        ),
    ]
