# Generated by Django 4.0.8 on 2023-02-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_publicreport_reconciled_report_reconciled'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('police_station', 'reference', 'entry_date'), name='unique_report'),
        ),
    ]
