# Generated by Django 4.0.8 on 2023-02-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_report_unique_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicreport',
            name='reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
