# Generated by Django 4.0.8 on 2023-02-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_report_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='gde_or_fir',
            field=models.CharField(default='GDE', max_length=3),
            preserve_default=False,
        ),
    ]
