# Generated by Django 4.0.8 on 2023-02-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_report_gde_or_fir'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_report',
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('police_station', 'reference', 'entry_date', 'gde_or_fir'), name='unique_report'),
        ),
    ]
