# Generated by Django 4.0.8 on 2023-02-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_is_correct',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='publicreportmatch',
            name='match_is_correct',
            field=models.BooleanField(null=True),
        ),
    ]
