# Generated by Django 4.0.8 on 2023-02-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='telephone',
            field=models.CharField(default='9830425757', max_length=10),
            preserve_default=False,
        ),
    ]
