# Generated by Django 4.0.8 on 2023-05-01 15:17

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_create_vector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicreport',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=128, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=128, null=True),
        ),
        migrations.AddIndex(
            model_name='publicreport',
            index=pgvector.django.IvfflatIndex(fields=['embedding'], lists=100, name='public_report_embeddings_index', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='report',
            index=pgvector.django.IvfflatIndex(fields=['embedding'], lists=100, name='report_embeddings_index', opclasses=['vector_cosine_ops']),
        ),
    ]
