# Generated by Django 4.0.8 on 2023-01-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name='Name of District')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('UNAUTHORIZED', 'Unauthorized'), ('VIEWER', 'Viewer'), ('PS_ADMIN', 'PS_Admin'), ('DISTRICT_ADMIN', 'District_Admin'), ('CID_ADMIN', 'CID_Admin'), ('ADMIN', 'Admin')], default='UNAUTHORIZED', max_length=50, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_oc',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sp_or_cp',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rank of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Cellphone of User'),
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('police_stationId', models.CharField(max_length=50, verbose_name='Legacy Id')),
                ('name', models.CharField(max_length=50, verbose_name='Name of PS')),
                ('ps_with_distt', models.CharField(blank=True, max_length=250, null=True, verbose_name='Full Name of PS')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude of PS')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude of PS')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address of PS')),
                ('officer_in_charge', models.CharField(blank=True, max_length=250, null=True, verbose_name='O/C of PS')),
                ('office_telephone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Office Numberof PS')),
                ('telephones', models.CharField(blank=True, max_length=250, null=True, verbose_name='Telephone Numbers of PS')),
                ('emails', models.CharField(blank=True, max_length=250, null=True, verbose_name='Email ID of PS')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.district')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.district'),
        ),
        migrations.AddField(
            model_name='user',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.policestation'),
        ),
    ]
