# Generated by Django 4.0.8 on 2023-02-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_district_user_category_user_is_oc_user_is_sp_or_cp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['pk']},
        ),
    ]
